// The NCAA data object. The entire page is generated from these data objects. There is one for each division (e.g. east, west, midwest, south)
  var east = [
    {
      // This determines the direct location of the team on the bracket.
      // The seed number is placed in the lower left corner of each table.
      // Options: #1 - #16
      seedNumber : 1,
      // This is the name that will display in the table row.
      // It was decided on that the city/state would display instead of the
      // full team name.
      // Options: *** Will be determined day before launch ***
      // Example: Kentucky, Virginia, Virginia Tech, Villanova
      schoolName : "Kentucky",
      // This determines the school's abbreviation. This is super important
      // as the name switch to the abbreviation on mobile.
      abbreviation : "KY",
      // Click through link:
      ctaLink: "/s/fan-shop",
      // The rounds determine which column the team is populated in.
      // During the beginning rounds, every team will have first round set to 'true'
      // Only the teams that advance to the next round will get a 'true' on the
      // proceeding rounds.
      // Options: Boolean
      firstRound : true,
      secondRound : true,
      thirdRound : true,
      fourthRound : true,
      // This determines whether the team has been eliminated or not.
      // This is technically optional as not every team will be eliminated but
      // its definitely required for those that are eliminated.
      // Options: Boolean
      eliminated : false,
      // This determines whether the team has won their division or not
      // This is technically optional as not every team will win their divison but
      // its definitely required for those that do.
      // Options: Boolean
      divisionWinner : true,
      // This determines whether the team has won the entire NCAA tournament
      // Only required for the overall winner of the tournament
      // Options: Boolean
      tournamentWinner : false
    },
    {
      seedNumber : 2,
      schoolName : "Villanova",
      abbreviation: "Nova",
      ctaLink: "",
      firstRound: true,
      secondRound : true,
      thirdRound : true,
      fourthRound : true,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },{
      seedNumber : 3,
      schoolName : "MT. ST. Marys",
      abbreviation: "MTSTM",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 4,
      schoolName : "DUKE",
      abbreviation: "DKE",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 5,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 6,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 7,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 8,
      schoolName : "Virgina",
      abbreviation: "VA",
      ctaLink: "/c/virginia-cavaliers-apparel-gear",
      firstRound: true,
      secondRound : true,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 9,
      schoolName : "Virginia Tech",
      abbreviation: "VA.Tch",
      ctaLink: "/c/footwear",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : true,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 10,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 11,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 12,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 13,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 14,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 15,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 16,
      schoolName : "Robert Morris",
      abbreviation: "RMU",
      ctaLink: "/s/fan-shop",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : true,
      divisionWinner : false,
      tournamentWinner : false
    }
  ];
  var west = [
    {
      seedNumber : 1,
      schoolName : "West Team",
      abbreviation: "WT",
      ctaLink: "/s/fan-shop",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 2,
      schoolName : "No CTA Team",
      abbreviation: "NCT",
      ctaLink: "",
      firstRound: true,
      secondRound : true,
      thirdRound : true,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },{
      seedNumber : 3,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 4,
      schoolName : "fjkghd",
      abbreviation: "dd",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : true,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 5,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 6,
      schoolName : "Baylor",
      abbreviation: "BLR",
      ctaLink: "",
      firstRound: true,
      secondRound : true,
      thirdRound : true,
      fourthRound : true,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 7,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 8,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 9,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 10,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 11,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 12,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 13,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 14,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 15,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 16,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    }
  ];
  var midwest = [
    {
      seedNumber : 1,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 2,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },{
      seedNumber : 3,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 4,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 5,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 6,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 7,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 8,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 9,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 10,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 11,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 12,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 13,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 14,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 15,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 16,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    }
  ];
  var south = [
    {
      seedNumber : 1,
      schoolName : "South Team",
      abbreviation: "ST",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 2,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },{
      seedNumber : 3,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 4,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 5,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 6,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 7,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 8,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 9,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 10,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 11,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 12,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 13,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 14,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 15,
      schoolName : "",
      abbreviation: "",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    },
    {
      seedNumber : 16,
      schoolName : " Other South Team",
      abbreviation: "OST",
      ctaLink: "",
      firstRound: true,
      secondRound : false,
      thirdRound : false,
      fourthRound : false,
      eliminated : false,
      divisionWinner : false,
      tournamentWinner : false
    }
  ];